#! /bin/bash
gitbook install
git push origin master
gitbook build
git branch -D gh-pages
git checkout --orphan gh-pages
git add .
git commit -m "clear old pages"
git push -f origin gh-pages
git rm --cached -r .
echo "*~" > .gitignore
echo "_book" >> .gitignore
git add .gitignore
git commit -m "Ignore some files"
cp -r _book/* .
git add .
git commit -m "Publish book"
git push -u origin gh-pages
git checkout master
